/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage { 'content' : string, 'role' : string }
export interface Goal {
  'name' : string,
  'unit' : string,
  'currentValue' : bigint,
  'targetValue' : bigint,
}
export interface Meal {
  'fat' : bigint,
  'carbs' : bigint,
  'date' : bigint,
  'calories' : bigint,
  'name' : string,
  'mealType' : MealType,
  'protein' : bigint,
}
export type MealType = { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'snack' : null } |
  { 'dinner' : null };
export interface StepCount { 'date' : bigint, 'steps' : bigint }
export interface UserProfile {
  'age' : bigint,
  'weight' : bigint,
  'height' : bigint,
  'fitnessGoals' : Array<Goal>,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Workout {
  'duration' : bigint,
  'date' : bigint,
  'caloriesBurned' : bigint,
  'workoutType' : WorkoutType,
}
export type WorkoutType = { 'other' : null } |
  { 'yoga' : null } |
  { 'strength' : null } |
  { 'cardio' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[ChatMessage], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getMeals' : ActorMethod<[], Array<Meal>>,
  'getStepCounts' : ActorMethod<[], Array<StepCount>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkouts' : ActorMethod<[], Array<Workout>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logMeal' : ActorMethod<[Meal], undefined>,
  'logStepCount' : ActorMethod<[StepCount], undefined>,
  'logWorkout' : ActorMethod<[Workout], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGoal' : ActorMethod<[Goal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];