/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Goal = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'currentValue' : IDL.Nat,
  'targetValue' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Nat,
  'height' : IDL.Nat,
  'fitnessGoals' : IDL.Vec(Goal),
  'name' : IDL.Text,
});
export const MealType = IDL.Variant({
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'snack' : IDL.Null,
  'dinner' : IDL.Null,
});
export const Meal = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'date' : IDL.Int,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'mealType' : MealType,
  'protein' : IDL.Nat,
});
export const StepCount = IDL.Record({ 'date' : IDL.Int, 'steps' : IDL.Nat });
export const WorkoutType = IDL.Variant({
  'other' : IDL.Null,
  'yoga' : IDL.Null,
  'strength' : IDL.Null,
  'cardio' : IDL.Null,
});
export const Workout = IDL.Record({
  'duration' : IDL.Nat,
  'date' : IDL.Int,
  'caloriesBurned' : IDL.Nat,
  'workoutType' : WorkoutType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func([ChatMessage], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getMeals' : IDL.Func([], [IDL.Vec(Meal)], ['query']),
  'getStepCounts' : IDL.Func([], [IDL.Vec(StepCount)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logMeal' : IDL.Func([Meal], [], []),
  'logStepCount' : IDL.Func([StepCount], [], []),
  'logWorkout' : IDL.Func([Workout], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGoal' : IDL.Func([Goal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Goal = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'currentValue' : IDL.Nat,
    'targetValue' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'fitnessGoals' : IDL.Vec(Goal),
    'name' : IDL.Text,
  });
  const MealType = IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'snack' : IDL.Null,
    'dinner' : IDL.Null,
  });
  const Meal = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'date' : IDL.Int,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'mealType' : MealType,
    'protein' : IDL.Nat,
  });
  const StepCount = IDL.Record({ 'date' : IDL.Int, 'steps' : IDL.Nat });
  const WorkoutType = IDL.Variant({
    'other' : IDL.Null,
    'yoga' : IDL.Null,
    'strength' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const Workout = IDL.Record({
    'duration' : IDL.Nat,
    'date' : IDL.Int,
    'caloriesBurned' : IDL.Nat,
    'workoutType' : WorkoutType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func([ChatMessage], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getMeals' : IDL.Func([], [IDL.Vec(Meal)], ['query']),
    'getStepCounts' : IDL.Func([], [IDL.Vec(StepCount)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logMeal' : IDL.Func([Meal], [], []),
    'logStepCount' : IDL.Func([StepCount], [], []),
    'logWorkout' : IDL.Func([Workout], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGoal' : IDL.Func([Goal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };